### ISSUE TITLE
502, Bad Gateway

### ISSUE THREAD

**Issue by NTohan** [mendersoftware/mender-server#108]
The main branch on hash 4ff5436319a761e9382da8762353c3124713a6d2 with `docker compose up -d
` and visiting https://localhost/ leads to `{"error": {"status_code": 502,"message": "Bad Gateway"}}`

Environment: 
```
 $ docker compose version
Docker Compose version v2.29.7
```

```
$ wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4317
```

**Comment by NTohan** [comment]
[alfrunes:fix-workflow-certs](https://github.com/mendersoftware/mender-server/pull/107/commits/4c52bb23bf4ef011fce18b9ed94cf6923e7cec44) solves the issue for me. Please feel free to close the issue after the MR is merged to the main branch. Thank you.

**Comment by alfrunes** [comment]
Thank you for reporting. This repository is still under development as we are migrating our Quality Assurance infrastructure from the old repositories.
If you happen to encounter a similar issue, could you also attach the output of `docker compose ps` and possibly some relevant `docker compose logs`?
